### ISSUE TITLE
review / redux

### ISSUE THREAD

**Issue by fabienjuif** [atomrc/atomrc.github.io#1]
## action formats

https://github.com/atomrc/atomrc.github.io/blob/talk/nantesjs_doyoubuzz-cycle/_talks/2017-11-16-nantesjs-doyoubuzz-cycle.html#L479

source: https://redux.js.org/docs/basics/Actions.html

 - You should dispatch an object, not a simple string. 
 - Usually the object have a `type` field, but this is a convention.
 - We create actions factory very often `const add = (todo) => ({ type: 'ADD_TODO', payload: todo })`

## redux-thunk
https://github.com/atomrc/atomrc.github.io/blob/837a817d92f72937ec6713aa9228e5c3e5cb119f/_talks/2017-11-16-nantesjs-doyoubuzz-cycle.html#L482

 - With the `redux-thunk` you use middleware you can (you should) do : 
```
dispatch(fetchCVCompletionAction(cv))
```
 - This is the purpose of the middleware to know if the action (what returns `fetchCVCompletionAction(cv)`) is an object, or a function 😉

**Comment by atomrc** [comment]
Very true and accurate. Will fix right away :)

Thanks for the review 👍
